# Generated by Django 5.2.17 on 2026-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=32, unique=True)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("eta", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
